SA14/Tests: Remove masking the resultproxy and fix setup of fake cursors
Beforehand, after observing errors like::

  RuntimeError: number of values in row (1) differ from number of column processors (0)

we decided to take the `resultproxy` out of the equation in order to
work on the real gist of SQLAlchemy 1.4 compatibility.

When looking at this again, it turned out that the root cause have been
inaccuracies when setting up fake cursors within the test cases.
SQLAlchemy <1.4 might have been more forgiving on that, but >=1.4 isn't.