SA14/Tests: Declare column expressions for `_score` as `literal_column`
With the original code, SA14 would croak like::

    sqlalchemy.exc.ArgumentError: Textual column expression '_score' should be
    explicitly declared with text('_score'), or use column('_score') for more
    specificity

However, when using the `sa.text` type, as suggested, older SQLAlchemy
versions will croak in this manner::

    sqlalchemy.exc.InvalidRequestError: SQL expression, column, or mapped entity expected - got '<sqlalchemy.sql.elements.TextClause object at 0x10c0f7460>'

The `sa.column` type also will not work, because it would get rendered
with quotes as `"_score"`.

> `literal_column()` is similar to `column()`, except that it is more
> often used as a “standalone” column expression that renders exactly
> as stated.
>
> -- https://docs.sqlalchemy.org/en/14/core/sqlelement.html#sqlalchemy.sql.expression.literal_column

::

    - SELECT characters.name AS characters_name, _score FROM characters WHERE match(characters.name, ?)
    + SELECT characters.name AS characters_name, "_score" FROM characters WHERE match(characters.name, ?)

Settling with the `sa.literal_column` type resolved any woes.