SA20: Fix `unexpected keyword argument 'info_cache'` on introspection
Both methods `CrateDialect.{has_schema,has_table}` need to accept and
forward keyword arguments, in order to comply to the intended interface,
starting with SQLAlchemy 2.0.

Otherwise, those errors would be raised:

- TypeError: CrateDialect.has_schema() got an unexpected keyword argument 'info_cache'
- TypeError: CrateDialect.has_table() got an unexpected keyword argument 'info_cache'