CI: Fix HTTP certificate error when requesting example.org from GHA
ConnectionError: Server not available, exception:
HTTPSConnectionPool(host='example.org', port=443):
Max retries exceeded with url: Caused by SSLCertVerificationError
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
unable to get local issuer certificate (_ssl.c:1081)